version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      timezone: "Europe/Sofia"
    commit-message:
      prefix: "[github-action] "
    assignees:
      - "IliyanKostov9"
    reviewers:
      - "IliyanKostov9"
    labels:
      - "github-action"
      - "dependencies"
